### ISSUE TITLE
exa is deprecated

### ISSUE THREAD

**Issue by zombiehoffa** [CachyOS/cachyos-fish-config#7]
exa is deprecated.
https://github.com/ogham/exa
This is a problem because exa is a dependency of cachyos-fish-config, which is a dependency of cachyos-hyprland-settings.

solution: switch to the eza fork: https://github.com/eza-community/eza
or lsd: https://github.com/lsd-rs/lsd

My vote would be for lsd because it looks amazing.

**Comment by ptr1337** [comment]
> exa is deprecated. https://github.com/ogham/exa This is a problem because exa is a dependency of cachyos-fish-config, which is a dependency of cachyos-hyprland-settings.
> 
> solution: switch to the eza fork: https://github.com/eza-community/eza or lsd: https://github.com/lsd-rs/lsd
> 
> My vote would be for lsd because it looks amazing.

Thanks for pointing out, but this kinda just two days old, that exa got deprecated.
Lets see if the options are compatible with "eza".

**Comment by ptr1337** [comment]
https://github.com/CachyOS/cachyos-fish-config/commit/9043fe16928cd0240244701fa38911a70fce6d7f
