### ISSUE TITLE
The use of bat with MANPAGER causes wrong rendering

### ISSUE THREAD

**Issue by simonbcn** [CachyOS/cachyos-fish-config#8]
Github issue: https://github.com/sharkdp/bat/issues/2563

This is a problem that [has been known about since at least July of this year](https://forum.cachyos.org/d/178-man-pages-are-incorrectly-rendered), yet the same problematic configuration is still being used.

The workaround is add `set -x MANROFFOPT "-c"` to the  `/usr/share/cachyos-fish-config/cachyos-config.fish` or `.config/fish/config.fish` file.

**Comment by vnepogodin** [comment]
fixed here
https://github.com/CachyOS/cachyos-fish-config/commit/120e706db0f7e45520ba2d13088f108428298c0f

**Comment by simonbcn** [comment]
Okay, and what are you waiting for to apply it to the installation ISOs?

**Comment by ptr1337** [comment]
> Okay, and what are you waiting for to apply it to the installation ISOs?

Sorry. I thought I have updated directly after it.
Its updated now and you will get it after a sudo pacman -Syu
